# Data Explorer

A quick tour of all datasets assembled for the Chen, Kelly, and Xiu (2022) replication.
Data sources: RavenPack news analytics, CRSP stock/index data, and FRED macro series.

In [1]:
from pathlib import Path

import polars as pl

from settings import config

DATA_DIR = Path(config("DATA_DIR"))

---
## RavenPack

Dow Jones newswire articles scored by RavenPack's NLP analytics engine.

### ravenpack_djpr.parquet

Raw RavenPack Dow Jones Press Release analytics — one row per news article/entity event.

In [2]:
rp = pl.scan_parquet(DATA_DIR / "ravenpack_djpr.parquet")
shape = rp.select(pl.len()).collect().item()
cols = rp.collect_schema().names()
print(f"Rows: {shape:,}  |  Columns: {len(cols)}")
print(f"Columns: {cols}")

Rows: 28,808,984  |  Columns: 25
Columns: ['timestamp_utc', 'rp_story_id', 'rp_entity_id', 'entity_type', 'entity_name', 'country_code', 'relevance', 'event_sentiment_score', 'event_relevance', 'event_similarity_key', 'event_similarity_days', 'topic', 'rp_group', 'rp_type', 'sub_type', 'property', 'fact_level', 'category', 'news_type', 'rp_source_id', 'source_name', 'provider_id', 'provider_story_id', 'headline', 'css']

In [3]:
rp.head(5).collect()

shape: (5, 25)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ timestamp_ ┆ rp_story_i ┆ rp_entity_ ┆ entity_ty ┆ … ┆ provider_ ┆ provider_ ┆ headline  ┆ css   │
│ utc        ┆ d          ┆ id         ┆ pe        ┆   ┆ id        ┆ story_id  ┆ ---       ┆ ---   │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ f64   │
│ datetime[n ┆ str        ┆ str        ┆ str       ┆   ┆ str       ┆ str       ┆           ┆       │
│ s]         ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 2000-01-01 ┆ 52D513EA90 ┆ 047E26     ┆ COMP      ┆ … ┆ DJ        ┆ DN2000010 ┆ Sprint    ┆ -0.06 │
│ 17:52:28   ┆ 40443376A6 ┆            ┆           ┆   ┆           ┆ 1000112   ┆ Says No   ┆       │
│            ┆ B1747B0FA8 ┆            ┆           ┆   ┆           ┆           ┆ Y2K       ┆       │
│            ┆ …          ┆            ┆           ┆   ┆           ┆           ┆ Rollover  ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ Pr…       ┆       │
│ 2000-01-01 ┆ 96F65B2BE4 ┆ 047E26     ┆ COMP      ┆ … ┆ DJ        ┆ DN2000010 ┆ Sprint    ┆ -0.06 │
│ 17:52:28   ┆ 1EEFA2ACE9 ┆            ┆           ┆   ┆           ┆ 1000112   ┆ Says No   ┆       │
│            ┆ 1BC7D0F550 ┆            ┆           ┆   ┆           ┆           ┆ Y2K       ┆       │
│            ┆ …          ┆            ┆           ┆   ┆           ┆           ┆ Rollover  ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ Pr…       ┆       │
│ 2000-01-01 ┆ 32E2DF0E44 ┆ 248F44     ┆ COMP      ┆ … ┆ DJ        ┆ DN2000010 ┆ Air       ┆ 0.0   │
│ 19:11:58   ┆ 9A5530F320 ┆            ┆           ┆   ┆           ┆ 1000121   ┆ Traffic   ┆       │
│            ┆ 29BAC016B8 ┆            ┆           ┆   ┆           ┆           ┆ -2: Amtra ┆       │
│            ┆ …          ┆            ┆           ┆   ┆           ┆           ┆ k,General ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ …         ┆       │
│ 2000-01-01 ┆ 5827127FF7 ┆ 248F44     ┆ COMP      ┆ … ┆ DJ        ┆ DN2000010 ┆ Air       ┆ 0.0   │
│ 19:11:58   ┆ 4AC65C491D ┆            ┆           ┆   ┆           ┆ 1000121   ┆ Traffic   ┆       │
│            ┆ BCC82DE130 ┆            ┆           ┆   ┆           ┆           ┆ -2: Amtra ┆       │
│            ┆ …          ┆            ┆           ┆   ┆           ┆           ┆ k,General ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ …         ┆       │
│ 2000-01-01 ┆ 64A2437578 ┆ 61B81B     ┆ COMP      ┆ … ┆ DJ        ┆ DN2000010 ┆ PNC Bank  ┆ 0.04  │
│ 18:02:50   ┆ 1C0F561C0C ┆            ┆           ┆   ┆           ┆ 1000113   ┆ Says      ┆       │
│            ┆ 1E6F160682 ┆            ┆           ┆   ┆           ┆           ┆ Computer  ┆       │
│            ┆ …          ┆            ┆           ┆   ┆           ┆           ┆ Systems…  ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

In [4]:
rp.select(
    pl.col("timestamp_utc").min().alias("earliest"),
    pl.col("timestamp_utc").max().alias("latest"),
).collect()

shape: (1, 2)
┌─────────────────────┬─────────────────────────┐
│ earliest            ┆ latest                  │
│ ---                 ┆ ---                     │
│ datetime[ns]        ┆ datetime[ns]            │
╞═════════════════════╪═════════════════════════╡
│ 2000-01-01 00:24:51 ┆ 2019-06-29 22:00:11.548 │
└─────────────────────┴─────────────────────────┘

### ravenpack_djpr_with_permno.parquet

RavenPack articles linked to CRSP PERMNOs via the crosswalk table.

In [5]:
rp_permno = pl.scan_parquet(DATA_DIR / "ravenpack_djpr_with_permno.parquet")
shape = rp_permno.select(pl.len()).collect().item()
cols = rp_permno.collect_schema().names()
print(f"Rows: {shape:,}  |  Columns: {len(cols)}")
print(f"Columns: {cols}")

Rows: 28,147,995  |  Columns: 27
Columns: ['timestamp_utc', 'rp_story_id', 'rp_entity_id', 'entity_type', 'entity_name', 'country_code', 'relevance', 'event_sentiment_score', 'event_relevance', 'event_similarity_key', 'event_similarity_days', 'topic', 'rp_group', 'rp_type', 'sub_type', 'property', 'fact_level', 'category', 'news_type', 'rp_source_id', 'source_name', 'provider_id', 'provider_story_id', 'headline', 'css', 'permno', '__index_level_0__']

In [6]:
rp_permno.head(5).collect()

shape: (5, 27)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬───────┬────────┬────────────┐
│ timestamp_ ┆ rp_story_i ┆ rp_entity_ ┆ entity_typ ┆ … ┆ headline   ┆ css   ┆ permno ┆ __index_le │
│ utc        ┆ d          ┆ id         ┆ e          ┆   ┆ ---        ┆ ---   ┆ ---    ┆ vel_0__    │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ str        ┆ f64   ┆ i64    ┆ ---        │
│ datetime[n ┆ str        ┆ str        ┆ str        ┆   ┆            ┆       ┆        ┆ i64        │
│ s]         ┆            ┆            ┆            ┆   ┆            ┆       ┆        ┆            │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════╪════════╪════════════╡
│ 2000-01-01 ┆ 52D513EA90 ┆ 047E26     ┆ COMP       ┆ … ┆ Sprint     ┆ -0.06 ┆ 39087  ┆ 0          │
│ 17:52:28   ┆ 40443376A6 ┆            ┆            ┆   ┆ Says No    ┆       ┆        ┆            │
│            ┆ B1747B0FA8 ┆            ┆            ┆   ┆ Y2K        ┆       ┆        ┆            │
│            ┆ …          ┆            ┆            ┆   ┆ Rollover   ┆       ┆        ┆            │
│            ┆            ┆            ┆            ┆   ┆ Pr…        ┆       ┆        ┆            │
│ 2000-01-01 ┆ 96F65B2BE4 ┆ 047E26     ┆ COMP       ┆ … ┆ Sprint     ┆ -0.06 ┆ 39087  ┆ 1          │
│ 17:52:28   ┆ 1EEFA2ACE9 ┆            ┆            ┆   ┆ Says No    ┆       ┆        ┆            │
│            ┆ 1BC7D0F550 ┆            ┆            ┆   ┆ Y2K        ┆       ┆        ┆            │
│            ┆ …          ┆            ┆            ┆   ┆ Rollover   ┆       ┆        ┆            │
│            ┆            ┆            ┆            ┆   ┆ Pr…        ┆       ┆        ┆            │
│ 2000-01-01 ┆ 32E2DF0E44 ┆ 248F44     ┆ COMP       ┆ … ┆ Air        ┆ 0.0   ┆ 12079  ┆ 2          │
│ 19:11:58   ┆ 9A5530F320 ┆            ┆            ┆   ┆ Traffic    ┆       ┆        ┆            │
│            ┆ 29BAC016B8 ┆            ┆            ┆   ┆ -2: Amtrak ┆       ┆        ┆            │
│            ┆ …          ┆            ┆            ┆   ┆ ,General…  ┆       ┆        ┆            │
│ 2000-01-01 ┆ 5827127FF7 ┆ 248F44     ┆ COMP       ┆ … ┆ Air        ┆ 0.0   ┆ 12079  ┆ 3          │
│ 19:11:58   ┆ 4AC65C491D ┆            ┆            ┆   ┆ Traffic    ┆       ┆        ┆            │
│            ┆ BCC82DE130 ┆            ┆            ┆   ┆ -2: Amtrak ┆       ┆        ┆            │
│            ┆ …          ┆            ┆            ┆   ┆ ,General…  ┆       ┆        ┆            │
│ 2000-01-01 ┆ 64A2437578 ┆ 61B81B     ┆ COMP       ┆ … ┆ PNC Bank   ┆ 0.04  ┆ 60442  ┆ 4          │
│ 18:02:50   ┆ 1C0F561C0C ┆            ┆            ┆   ┆ Says       ┆       ┆        ┆            │
│            ┆ 1E6F160682 ┆            ┆            ┆   ┆ Computer   ┆       ┆        ┆            │
│            ┆ …          ┆            ┆            ┆   ┆ Systems…   ┆       ┆        ┆            │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴───────┴────────┴────────────┘

In [7]:
# PERMNO coverage
total = rp_permno.select(pl.len()).collect().item()
matched = rp_permno.filter(pl.col("permno").is_not_null()).select(pl.len()).collect().item()
n_permnos = rp_permno.select(pl.col("permno").n_unique()).collect().item()
print(f"Total rows: {total:,}")
print(f"Rows with PERMNO: {matched:,} ({matched / total * 100:.1f}%)")
print(f"Unique PERMNOs: {n_permnos:,}")

Total rows: 28,147,995
Rows with PERMNO: 28,147,995 (100.0%)
Unique PERMNOs: 10,626

### raven_crsp_crosswalk.parquet

Maps RavenPack entity IDs to CRSP PERMNOs.

In [8]:
crosswalk = pl.read_parquet(DATA_DIR / "raven_crsp_crosswalk.parquet")
print(f"Shape: {crosswalk.shape}")
crosswalk.head(5)

Shape: (16376, 2)

shape: (5, 2)
┌────────┬──────────────┐
│ permno ┆ rp_entity_id │
│ ---    ┆ ---          │
│ i64    ┆ str          │
╞════════╪══════════════╡
│ 57293  ┆ 5F8A7F       │
│ 14704  ┆ 8FEF3B       │
│ 21971  ┆ 23E688       │
│ 12030  ┆ 812BD2       │
│ 80804  ┆ ECC614       │
└────────┴──────────────┘

In [9]:
print(f"Unique RavenPack entities: {crosswalk['rp_entity_id'].n_unique()}")
print(f"Unique PERMNOs: {crosswalk['permno'].n_unique()}")

Unique RavenPack entities: 15799
Unique PERMNOs: 16242

---
## CRSP

Stock and index returns from the Center for Research in Security Prices.

### CRSP_MSF_INDEX_INPUTS.parquet

Monthly stock file — individual security returns and market cap used as index inputs.

In [10]:
msf = pl.read_parquet(DATA_DIR / "CRSP_MSF_INDEX_INPUTS.parquet")
print(f"Shape: {msf.shape}")
print(f"Columns: {msf.columns}")
msf.head(5)

Shape: (4447518, 24)
Columns: ['permno', 'permco', 'date', 'ret', 'retx', 'shrout', 'prc', 'vol', 'cfacshr', 'cfacpr', 'primaryexch', 'siccd', 'naics', 'issuertype', 'securitytype', 'securitysubtype', 'sharetype', 'usincflg', 'tradingstatusflg', 'altprc', 'adj_shrout', 'adj_prc', 'market_cap', '__index_level_0__']

shape: (5, 24)
┌────────┬────────┬─────────────┬───────────┬───┬────────────┬──────────┬────────────┬─────────────┐
│ permno ┆ permco ┆ date        ┆ ret       ┆ … ┆ adj_shrout ┆ adj_prc  ┆ market_cap ┆ __index_lev │
│ ---    ┆ ---    ┆ ---         ┆ ---       ┆   ┆ ---        ┆ ---      ┆ ---        ┆ el_0__      │
│ i64    ┆ i64    ┆ datetime[ns ┆ f64       ┆   ┆ f64        ┆ f64      ┆ f64        ┆ ---         │
│        ┆        ┆ ]           ┆           ┆   ┆            ┆          ┆            ┆ i64         │
╞════════╪════════╪═════════════╪═══════════╪═══╪════════════╪══════════╪════════════╪═════════════╡
│ 10000  ┆ 7952   ┆ 1986-01-31  ┆ 0.707317  ┆ … ┆ 3.68e6     ┆ 4.375    ┆ 1.61e7     ┆ 0           │
│        ┆        ┆ 00:00:00    ┆           ┆   ┆            ┆          ┆            ┆             │
│ 10000  ┆ 7952   ┆ 1986-02-28  ┆ -0.257143 ┆ … ┆ 3.68e6     ┆ 3.25     ┆ 1.196e7    ┆ 1           │
│        ┆        ┆ 00:00:00    ┆           ┆   ┆            ┆          ┆            ┆             │
│ 10000  ┆ 7952   ┆ 1986-03-31  ┆ 0.365385  ┆ … ┆ 3.68e6     ┆ 4.4375   ┆ 1.633e7    ┆ 2           │
│        ┆        ┆ 00:00:00    ┆           ┆   ┆            ┆          ┆            ┆             │
│ 10000  ┆ 7952   ┆ 1986-04-30  ┆ -0.098592 ┆ … ┆ 3.793e6    ┆ 4.0      ┆ 1.5172e7   ┆ 3           │
│        ┆        ┆ 00:00:00    ┆           ┆   ┆            ┆          ┆            ┆             │
│ 10000  ┆ 7952   ┆ 1986-05-30  ┆ -0.222656 ┆ … ┆ 3.793e6    ┆ 3.109375 ┆ 1.1794e7   ┆ 4           │
│        ┆        ┆ 00:00:00    ┆           ┆   ┆            ┆          ┆            ┆             │
└────────┴────────┴─────────────┴───────────┴───┴────────────┴──────────┴────────────┴─────────────┘

In [11]:
date_col = [c for c in msf.columns if "date" in c.lower()][0]
print(f"Date range: {msf[date_col].min()} to {msf[date_col].max()}")
print(f"Unique PERMNOs: {msf['permno'].n_unique():,}")

Date range: 1925-12-31 00:00:00 to 2024-12-31 00:00:00
Unique PERMNOs: 31,716

### CRSP_DSI.parquet

Daily stock index — aggregate market returns and counts.

In [12]:
dsi = pl.read_parquet(DATA_DIR / "CRSP_DSI.parquet")
print(f"Shape: {dsi.shape}")
dsi.head(5)

Shape: (26051, 11)

shape: (5, 11)
┌──────────────┬───────────┬───────────┬───────────┬───┬──────────┬────────┬────────┬────────┐
│ date         ┆ vwretd    ┆ vwretx    ┆ ewretd    ┆ … ┆ usdval   ┆ usdcnt ┆ sprtrn ┆ spindx │
│ ---          ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---    ┆ ---    ┆ ---    │
│ datetime[ns] ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64      ┆ f64    ┆ f64    ┆ f64    │
╞══════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪════════╪════════╪════════╡
│ 1925-12-31   ┆ null      ┆ null      ┆ null      ┆ … ┆ null     ┆ null   ┆ null   ┆ null   │
│ 00:00:00     ┆           ┆           ┆           ┆   ┆          ┆        ┆        ┆        │
│ 1926-01-02   ┆ 0.005689  ┆ 0.005689  ┆ 0.009516  ┆ … ┆ 2.7367e7 ┆ 494.0  ┆ null   ┆ null   │
│ 00:00:00     ┆           ┆           ┆           ┆   ┆          ┆        ┆        ┆        │
│ 1926-01-04   ┆ 0.000706  ┆ 0.000706  ┆ 0.00578   ┆ … ┆ 2.7480e7 ┆ 495.0  ┆ null   ┆ null   │
│ 00:00:00     ┆           ┆           ┆           ┆   ┆          ┆        ┆        ┆        │
│ 1926-01-05   ┆ -0.004821 ┆ -0.004867 ┆ -0.001927 ┆ … ┆ 2.7562e7 ┆ 499.0  ┆ null   ┆ null   │
│ 00:00:00     ┆           ┆           ┆           ┆   ┆          ┆        ┆        ┆        │
│ 1926-01-06   ┆ -0.000423 ┆ -0.000427 ┆ 0.001182  ┆ … ┆ 2.7527e7 ┆ 500.0  ┆ null   ┆ null   │
│ 00:00:00     ┆           ┆           ┆           ┆   ┆          ┆        ┆        ┆        │
└──────────────┴───────────┴───────────┴───────────┴───┴──────────┴────────┴────────┴────────┘

In [13]:
date_col = [c for c in dsi.columns if "date" in c.lower()][0]
print(f"Date range: {dsi[date_col].min()} to {dsi[date_col].max()}")

Date range: 1925-12-31 00:00:00 to 2024-12-31 00:00:00

### CRSP_MSIX.parquet

Monthly stock index returns.

In [14]:
msix = pl.read_parquet(DATA_DIR / "CRSP_MSIX.parquet")
print(f"Shape: {msix.shape}")
msix.head(5)

Shape: (1189, 35)

shape: (5, 35)
┌──────────────┬───────────┬──────────┬───────────┬───┬──────────┬────────┬──────────┬────────┐
│ caldt        ┆ vwretd    ┆ vwindd   ┆ vwretx    ┆ … ┆ totval   ┆ totcnt ┆ usdval   ┆ usdcnt │
│ ---          ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---    ┆ ---      ┆ ---    │
│ datetime[ns] ┆ f64       ┆ f64      ┆ f64       ┆   ┆ f64      ┆ i64    ┆ f64      ┆ f64    │
╞══════════════╪═══════════╪══════════╪═══════════╪═══╪══════════╪════════╪══════════╪════════╡
│ 1925-12-31   ┆ null      ┆ 1.474607 ┆ null      ┆ … ┆ 2.7487e7 ┆ 503    ┆ null     ┆ null   │
│ 00:00:00     ┆           ┆          ┆           ┆   ┆          ┆        ┆          ┆        │
│ 1926-01-30   ┆ 0.000561  ┆ 1.475434 ┆ -0.001395 ┆ … ┆ 2.7624e7 ┆ 506    ┆ 2.7413e7 ┆ 496.0  │
│ 00:00:00     ┆           ┆          ┆           ┆   ┆          ┆        ┆          ┆        │
│ 1926-02-27   ┆ -0.033046 ┆ 1.426677 ┆ -0.036587 ┆ … ┆ 2.6752e7 ┆ 514    ┆ 2.7601e7 ┆ 500.0  │
│ 00:00:00     ┆           ┆          ┆           ┆   ┆          ┆        ┆          ┆        │
│ 1926-03-31   ┆ -0.064002 ┆ 1.335367 ┆ -0.070021 ┆ … ┆ 2.5083e7 ┆ 519    ┆ 2.6684e7 ┆ 507.0  │
│ 00:00:00     ┆           ┆          ┆           ┆   ┆          ┆        ┆          ┆        │
│ 1926-04-30   ┆ 0.037029  ┆ 1.384814 ┆ 0.034043  ┆ … ┆ 2.5887e7 ┆ 521    ┆ 2.4921e7 ┆ 513.0  │
│ 00:00:00     ┆           ┆          ┆           ┆   ┆          ┆        ┆          ┆        │
└──────────────┴───────────┴──────────┴───────────┴───┴──────────┴────────┴──────────┴────────┘

---
## FRED

Macroeconomic time series from the Federal Reserve Economic Data service.

In [15]:
fred = pl.read_parquet(DATA_DIR / "fred.parquet")
print(f"Shape: {fred.shape}")
print(f"Columns: {fred.columns}")
fred.head(5)

Shape: (9699, 25)
Columns: ['GDP', 'CPIAUCNS', 'GDPC1', 'INDPRO', 'PAYEMS', 'DPCREDIT', 'EFFR', 'OBFR', 'SOFR', 'DFEDTARU', 'DFEDTARL', 'WALCL', 'TOTRESNS', 'TREAST', 'CURRCIR', 'GFDEBTN', 'WTREGEN', 'RRPONTSYAWARD', 'RRPONTSYD', 'RPONTSYD', 'WSDONTL', 'Gen_IORB', 'ONRRP_CTPY_LIMIT', 'ONRP_AGG_LIMIT', 'DATE']

shape: (5, 25)
┌──────┬──────────┬───────┬────────┬───┬──────────┬────────────────┬───────────────┬───────────────┐
│ GDP  ┆ CPIAUCNS ┆ GDPC1 ┆ INDPRO ┆ … ┆ Gen_IORB ┆ ONRRP_CTPY_LIM ┆ ONRP_AGG_LIMI ┆ DATE          │
│ ---  ┆ ---      ┆ ---   ┆ ---    ┆   ┆ ---      ┆ IT             ┆ T             ┆ ---           │
│ f64  ┆ f64      ┆ f64   ┆ f64    ┆   ┆ f64      ┆ ---            ┆ ---           ┆ datetime[ns]  │
│      ┆          ┆       ┆        ┆   ┆          ┆ f64            ┆ f64           ┆               │
╞══════╪══════════╪═══════╪════════╪═══╪══════════╪════════════════╪═══════════════╪═══════════════╡
│ null ┆ 9.8      ┆ null  ┆ null   ┆ … ┆ null     ┆ null           ┆ null          ┆ 1913-01-01    │
│      ┆          ┆       ┆        ┆   ┆          ┆                ┆               ┆ 00:00:00      │
│ null ┆ 9.8      ┆ null  ┆ null   ┆ … ┆ null     ┆ null           ┆ null          ┆ 1913-02-01    │
│      ┆          ┆       ┆        ┆   ┆          ┆                ┆               ┆ 00:00:00      │
│ null ┆ 9.8      ┆ null  ┆ null   ┆ … ┆ null     ┆ null           ┆ null          ┆ 1913-03-01    │
│      ┆          ┆       ┆        ┆   ┆          ┆                ┆               ┆ 00:00:00      │
│ null ┆ 9.8      ┆ null  ┆ null   ┆ … ┆ null     ┆ null           ┆ null          ┆ 1913-04-01    │
│      ┆          ┆       ┆        ┆   ┆          ┆                ┆               ┆ 00:00:00      │
│ null ┆ 9.7      ┆ null  ┆ null   ┆ … ┆ null     ┆ null           ┆ null          ┆ 1913-05-01    │
│      ┆          ┆       ┆        ┆   ┆          ┆                ┆               ┆ 00:00:00      │
└──────┴──────────┴───────┴────────┴───┴──────────┴────────────────┴───────────────┴───────────────┘

In [16]:
date_col = [c for c in fred.columns if "date" in c.lower()][0]
print(f"Date range: {fred[date_col].min()} to {fred[date_col].max()}")

Date range: 1913-01-01 00:00:00 to 2026-02-12 00:00:00

In [17]:
# Non-null counts per series
fred.select(pl.all().is_not_null().sum()).unpivot(
    variable_name="series",
    value_name="non_null_count",
).sort("non_null_count")

shape: (25, 2)
┌──────────┬────────────────┐
│ series   ┆ non_null_count │
│ ---      ┆ ---            │
│ str      ┆ u32            │
╞══════════╪════════════════╡
│ GFDEBTN  ┆ 239            │
│ GDP      ┆ 315            │
│ GDPC1    ┆ 315            │
│ PAYEMS   ┆ 1045           │
│ INDPRO   ┆ 1284           │
│ …        ┆ …              │
│ WTREGEN  ┆ 7872           │
│ WSDONTL  ┆ 7872           │
│ TOTRESNS ┆ 9147           │
│ CURRCIR  ┆ 9644           │
│ DATE     ┆ 9699           │
└──────────┴────────────────┘

---
## Market Data

Computed market-level return and volatility measures.

In [18]:
market = pl.read_parquet(DATA_DIR / "market_data.parquet")
print(f"Shape: {market.shape}")
market.head(5)

Shape: (402, 3)

shape: (5, 3)
┌───────────────┬───────────────────┬─────────────────────┐
│ market_return ┆ market_volatility ┆ date                │
│ ---           ┆ ---               ┆ ---                 │
│ f64           ┆ f64               ┆ datetime[ns]        │
╞═══════════════╪═══════════════════╪═════════════════════╡
│ -0.925869     ┆ 0.62667           ┆ 1984-01-01 00:00:00 │
│ -3.963452     ┆ 1.012833          ┆ 1984-02-01 00:00:00 │
│ 1.340771      ┆ 0.799722          ┆ 1984-03-01 00:00:00 │
│ 0.545069      ┆ 0.737019          ┆ 1984-04-01 00:00:00 │
│ -6.119101     ┆ 0.605125          ┆ 1984-05-01 00:00:00 │
└───────────────┴───────────────────┴─────────────────────┘

In [19]:
market.describe()

shape: (9, 4)
┌────────────┬───────────────┬───────────────────┬────────────────────────────┐
│ statistic  ┆ market_return ┆ market_volatility ┆ date                       │
│ ---        ┆ ---           ┆ ---               ┆ ---                        │
│ str        ┆ f64           ┆ f64               ┆ str                        │
╞════════════╪═══════════════╪═══════════════════╪════════════════════════════╡
│ count      ┆ 402.0         ┆ 402.0             ┆ 402                        │
│ null_count ┆ 0.0           ┆ 0.0               ┆ 0                          │
│ mean       ┆ 0.66851       ┆ 0.961621          ┆ 2000-09-15 09:43:52.835820 │
│ std        ┆ 4.337423      ┆ 0.600189          ┆ null                       │
│ min        ┆ -24.542803    ┆ 0.256884          ┆ 1984-01-01 00:00:00        │
│ 25%        ┆ -1.693331     ┆ 0.620898          ┆ 1992-05-01 00:00:00        │
│ 50%        ┆ 1.061761      ┆ 0.804608          ┆ 2000-10-01 00:00:00        │
│ 75%        ┆ 3.458121      ┆ 1.095015          ┆ 2009-02-01 00:00:00        │
│ max        ┆ 12.378003     ┆ 6.119488          ┆ 2017-06-01 00:00:00        │
└────────────┴───────────────┴───────────────────┴────────────────────────────┘